ci:
    autoupdate_schedule: quarterly
    autofix_prs: true
    autoupdate_commit_msg: 'chore(deps): [pre-commit.ci] autoupdate'
    autofix_commit_msg: 'chore: [pre-commit.ci] autofix'

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: check-toml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
          - id: check-json

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.12
      hooks:
          - id: actionlint

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.11.0.1
      hooks:
          - id: shellcheck

    - repo: https://github.com/scop/pre-commit-shfmt
      rev: v3.13.0-1
      hooks:
          - id: shfmt

    - repo: https://github.com/rbubley/mirrors-prettier
      rev: v3.9.6
      hooks:
          - id: prettier
            stages: [pre-commit]

    - repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: v0.23.2
      hooks:
          - id: markdownlint-cli2
            stages: [pre-commit]
            args:
                - --config
                - .markdownlint.yaml

    - repo: https://github.com/crate-ci/typos
      rev: v1.50.1
      hooks:
          - id: typos

    - repo: https://github.com/betterleaks/betterleaks
      rev: v1.8.1
      hooks:
          - id: betterleaks
